/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package billingsystem;

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        logUN = new javax.swing.JTextField();
        logBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        suBTN = new javax.swing.JButton();
        logT = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logP = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(330, 70, 80, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(330, 130, 70, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Log in As");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(330, 190, 100, 30);

        logUN.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(logUN);
        logUN.setBounds(420, 70, 250, 30);

        logBTN.setBackground(new java.awt.Color(204, 204, 204));
        logBTN.setForeground(new java.awt.Color(0, 0, 0));
        logBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/login (1).png"))); // NOI18N
        logBTN.setText("Login");
        logBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logBTNActionPerformed(evt);
            }
        });
        jPanel1.add(logBTN);
        logBTN.setBounds(330, 230, 90, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("I don't have an account!");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(330, 270, 190, 30);

        suBTN.setBackground(new java.awt.Color(204, 204, 204));
        suBTN.setForeground(new java.awt.Color(255, 0, 51));
        suBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/signup (1).png"))); // NOI18N
        suBTN.setText("Sign Up");
        suBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suBTNActionPerformed(evt);
            }
        });
        jPanel1.add(suBTN);
        suBTN.setBounds(510, 270, 100, 30);

        logT.setBackground(new java.awt.Color(255, 255, 255));
        logT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        logT.setForeground(new java.awt.Color(0, 0, 0));
        logT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select User Type", "Admin", "Customer", " " }));
        jPanel1.add(logT);
        logT.setBounds(420, 190, 250, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/salut-logo-ezgif.com-resize (1).gif"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 40, 280, 240);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("AmpereLink");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 280, 140, 24);

        logP.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(logP);
        logP.setBounds(420, 130, 250, 30);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(560, 160, 120, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logBTNActionPerformed

       String userType, userN, Password, query;
        
        String sUrl, sUser, sPass;
        
        Connection connection = null;
        sUrl = "jdbc:MYSQL://localhost:3306/ewb";
        sUser = "root";
        sPass = "";
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(sUrl, sUser, sPass);
            Statement st = con.createStatement();
            
                
             
              
            
           // Validate inputs
        if ("Select User Type".equals(logT.getSelectedItem()) || logUN.getText().isEmpty() || logP.getText().isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "Please fill all fields", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            userType = (String) logT.getSelectedItem();
            userN = logUN.getText();
            Password = logP.getText();

            // SQL query to verify user credentials
            query = "SELECT * FROM user WHERE username = '" + userN + "' AND password = '" + Password + "' AND userT = '" + userType + "'";
            ResultSet rs = st.executeQuery(query);

            if (rs.next()) {
                // Successful login
                JOptionPane.showMessageDialog(null, "Login successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
                String userName = rs.getString("name");
                String meterNumber = rs.getString("meter_Number"); 

                // Redirect to appropriate dashboard based on user type
                if ("Admin".equals(userType)) {
                    AdminDashboard adminDashboard = new AdminDashboard();
                    adminDashboard.setVisible(true);
                    adminDashboard.pack();
                    adminDashboard.setLocationRelativeTo(this);
                    
                } else if ("Customer".equals(userType)) {
                    CustomerDashboard customerDashboard = new CustomerDashboard(userName, meterNumber);
                    customerDashboard.setVisible(true);
                    customerDashboard.setLocationRelativeTo(this);
                }
                this.dispose(); // Close the current login window
            } else {
                // Invalid credentials
                JOptionPane.showMessageDialog(new JFrame(), "Invalid username, password, or user type", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(new JFrame(), "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
            
        

       
        
    }//GEN-LAST:event_logBTNActionPerformed

    private void suBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suBTNActionPerformed
       SIGNUP signup = new SIGNUP();
       signup.setVisible(true);
       signup.pack();
       signup.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_suBTNActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
        logP.setEchoChar((char) 0); // Show password
    } else {
        logP.setEchoChar('*'); // Hide password
    }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logBTN;
    private javax.swing.JPasswordField logP;
    private javax.swing.JComboBox<String> logT;
    private javax.swing.JTextField logUN;
    private javax.swing.JButton suBTN;
    // End of variables declaration//GEN-END:variables
}
