/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package billingsystem;

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class SIGNUP extends javax.swing.JFrame {

    /**
     * Creates new form SIGNUP
     */
    public SIGNUP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtN = new javax.swing.JTextField();
        txtUN = new javax.swing.JTextField();
        meterN = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        signUpbtn = new javax.swing.JButton();
        cmbUT = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 350));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Password");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 190, 110, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Create Account  As");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 30, 150, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Username");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 110, 150, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 150, 150, 30);

        txtN.setBackground(new java.awt.Color(255, 255, 255));
        txtN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtN.setForeground(new java.awt.Color(0, 0, 0));
        txtN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNActionPerformed(evt);
            }
        });
        jPanel1.add(txtN);
        txtN.setBounds(210, 150, 210, 30);

        txtUN.setBackground(new java.awt.Color(255, 255, 255));
        txtUN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUN.setForeground(new java.awt.Color(0, 0, 0));
        txtUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUNActionPerformed(evt);
            }
        });
        jPanel1.add(txtUN);
        txtUN.setBounds(210, 110, 210, 30);

        meterN.setBackground(new java.awt.Color(255, 255, 255));
        meterN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        meterN.setForeground(new java.awt.Color(0, 0, 0));
        meterN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                meterNFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                meterNFocusLost(evt);
            }
        });
        meterN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meterNActionPerformed(evt);
            }
        });
        jPanel1.add(meterN);
        meterN.setBounds(210, 70, 210, 30);

        loginBtn.setBackground(new java.awt.Color(204, 204, 204));
        loginBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(0, 0, 0));
        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/login (1).png"))); // NOI18N
        loginBtn.setText("Log in");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginBtn);
        loginBtn.setBounds(230, 300, 110, 30);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("I already have an account!");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 300, 190, 30);

        signUpbtn.setBackground(new java.awt.Color(204, 204, 204));
        signUpbtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        signUpbtn.setForeground(new java.awt.Color(255, 0, 51));
        signUpbtn.setText("Sign Up");
        signUpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpbtnActionPerformed(evt);
            }
        });
        jPanel1.add(signUpbtn);
        signUpbtn.setBounds(40, 260, 90, 30);

        cmbUT.setBackground(new java.awt.Color(255, 255, 255));
        cmbUT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cmbUT.setForeground(new java.awt.Color(0, 0, 0));
        cmbUT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select User Type", "Customer" }));
        cmbUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUTActionPerformed(evt);
            }
        });
        jPanel1.add(cmbUT);
        cmbUT.setBounds(210, 30, 210, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/signupImage (2).png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(450, 30, 220, 230);

        txtP.setBackground(new java.awt.Color(255, 255, 255));
        txtP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtP.setForeground(new java.awt.Color(0, 0, 0));
        txtP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPActionPerformed(evt);
            }
        });
        jPanel1.add(txtP);
        txtP.setBounds(210, 190, 210, 30);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Meter Number");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 70, 140, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meterNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meterNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meterNActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        LOGIN login = new LOGIN();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_loginBtnActionPerformed

    private void signUpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpbtnActionPerformed
     System.out.println("Sign Up clicked");
    String userType, userN, password, name, query, meterNum;
    
    String sUrl = "jdbc:MYSQL://localhost:3306/ewb";
    String sUser = "root";
    String sPass = "";
    
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection(sUrl, sUser, sPass);
        Statement st = con.createStatement();
        
        // Get field values
        userType = (String) cmbUT.getSelectedItem();
        userN = txtUN.getText().trim();
        password = txtP.getText().trim();
        name = txtN.getText().trim();
        meterNum = meterN.getText().trim();

        // Validation
        if ("Select User Type".equals(userType) || userN.isEmpty() || password.isEmpty() || name.isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "Please fill all required fields", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(userN.isEmpty()){
            JOptionPane.showMessageDialog(new JFrame(), "Please fill the Username");
            return;
        }else if(password.isEmpty()){
            JOptionPane.showMessageDialog(new JFrame(), "Password is empty");
            return;
        }else if(name.isEmpty()){
            JOptionPane.showMessageDialog(new JFrame(), "Name is empty");
            return;
        }   
        
        if (!"Admin".equals(userType) && meterNum.isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "Please provide a Meter Number for Customers", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validate meter number in the database
            
            String query1 = "SELECT name FROM customer WHERE meter_number = ?";
            PreparedStatement pst = con.prepareStatement(query1);
            pst.setString(1, meterNum);
            ResultSet rs = pst.executeQuery();

            if (!rs.next()) {
                JOptionPane.showMessageDialog(new JFrame(), "Invalid Meter Number. Please contact admin.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

        // Build query based on user type
        if ("Admin".equals(userType)) {
            query = "INSERT INTO user (userT, username, password, name) VALUES " +
                    "('" + userType + "', '" + userN + "', '" + password + "', '" + name + "')";
        } else {
            query = "INSERT INTO user (userT, username, password, name, meter_number) VALUES " +
                    "('" + userType + "', '" + userN + "', '" + password + "', '" + name + "', '" + meterNum + "')";
        }

        // Execute query
        st.execute(query);

        // Clear fields after successful insertion
        txtUN.setText("");
        txtP.setText("");
        txtN.setText("");
        meterN.setText("");

        JOptionPane.showMessageDialog(null, "Account has been created successfully!");

    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
        JOptionPane.showMessageDialog(new JFrame(), "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_signUpbtnActionPerformed

    private void cmbUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUTActionPerformed

        String selectedUserType = (String) cmbUT.getSelectedItem();
    
    if ("Admin".equals(selectedUserType)) {
        // Hide Meter Number label and text field
        jLabel3.setVisible(false);
        meterN.setVisible(false);
    } else {
        // Show Meter Number label and text field
        jLabel3.setVisible(true);
        meterN.setVisible(true);
    }
          
            
    }//GEN-LAST:event_cmbUTActionPerformed

    private void txtUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUNActionPerformed

    private void txtPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPActionPerformed

    private void txtNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNActionPerformed

    private void meterNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_meterNFocusGained

       
        
        
        
    }//GEN-LAST:event_meterNFocusGained

    private void meterNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_meterNFocusLost
        String meterNum = meterN.getText().trim();
    String sUrl = "jdbc:MYSQL://localhost:3306/ewb";
    String sUser = "root";
    String sPass = "";

    if (!meterNum.isEmpty()) {
        try {
            // Connect to the database
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(sUrl, sUser, sPass);

            // Query to fetch the name based on meter number
            String query = "SELECT name FROM customer WHERE meter_number = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, meterNum);

            ResultSet rs = pst.executeQuery();

            // Check if a result is returned
            if (rs.next()) {
                String name = rs.getString("name");
                txtN.setText(name); // Set the name in the name field
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "Meter number not found", "Error", JOptionPane.ERROR_MESSAGE);
                txtN.setText(""); // Clear the name field
            }

            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_meterNFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIGNUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbUT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField meterN;
    private javax.swing.JButton signUpbtn;
    private javax.swing.JTextField txtN;
    private javax.swing.JTextField txtP;
    private javax.swing.JTextField txtUN;
    // End of variables declaration//GEN-END:variables
}
